### ISSUE TITLE
Poezio is missing on Flathub.org?

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/io.poez.Poezio#1]
The Poezio page is missing on the Flathub website and the Flatpak is also missing in GNOME Software. It looks like that there is some issue with the AppStream metadata.
![captura de tela de 2018-09-07 19-53-55](https://user-images.githubusercontent.com/26097419/45246460-ca818a00-b2d7-11e8-8c03-984b7d9e9e33.png)

**Comment by linkmauve** [comment]
Indeed, I noticed that a few weeks ago and asked there, but got no answer: https://github.com/flathub/flathub/pull/548#issuecomment-417717275

**Comment by LeandroStanger** [comment]
https://github.com/flathub/com.adobe.Flash-Player-Projector/issues/2#issuecomment-419870858

**Comment by jgarciao** [comment]
I just bump into this issue.

Flathub.org gets the information about the apps from the appstream.xml file generated in the ostree repo. You can see the contents in your computer opening this file: /var/lib/flatpak/appstream/flathub/x86_64/active/appstream.xml

This app is not appearing in the website because it has some issues in the appstream information:
- `<component> `should be `<component type="desktop">`
- there is an `<icon>` tag for 64x6x, but 128x128 is also required
- `<description>` tag is not defined

There is a list of common problems in appdata here
https://github.com/hughsie/appstream-glib/issues/263

**Comment by linkmauve** [comment]
poezio isn’t a desktop application though, so I’m not too fond of pretending it is, especially since appstream defines such a `console-application` component.

What would be a good way forward?

**Comment by barthalion** [comment]
As long as poezio has some sort of terminal UI, I'd say it's fine. You can add `Terminal=true` to desktop launcher like Cointop: https://github.com/miguelmota/cointop/blob/master/.flathub/com.github.miguelmota.Cointop.desktop

https://flathub.org/apps/details/com.github.miguelmota.Cointop

**Comment by barthalion** [comment]
Note appdata validation for desktop applications is more strict: https://flathub.org/builds/#/builders/35/builds/2410

**Comment by linkmauve** [comment]
Thanks for the guidance, I’ll keep the `type="console-application"` upstream and run `sed` in the flatpak script to make flathub happy.

The two `tag-missing` errors area already fixed upstream, we’re planning a 0.13.1 this week to ship that and some more fixes, after which poezio should finally be available on flathub! \o/

**Comment by linkmauve** [comment]
With the release of 0.13.1, poezio should now be available on flathub, finally!

Although it’s stuck “LOADING ...” for me, so maybe I’ll wait a while before I close this issue: https://flathub.org/apps/details/io.poez.Poezio

And it still won’t work until https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/253 is fixed.

I’ve reported https://github.com/flathub/flathub/issues/1559 as well.

**Comment by bilelmoussaoui** [comment]
If it's a console application, you shouldn't be pretending it's a desktop one really. That's not the way to go forward.
We want console applications to be displayed on the website frontend, but merge request are welcome for that:)

**Comment by linkmauve** [comment]
Do you have an issue somewhere listing the missing pieces for that?

**Comment by bilelmoussaoui** [comment]
https://github.com/flathub/linux-store-frontend/issues/184

**Comment by linkmauve** [comment]
Alright, as per https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/253#note_368039297 I have now updated this package for 20.08beta which seems to finally start properly!  I’m still not too sure how to trigger a build, nor when it will be available on flathub, but this should be the last streak!

Edit: meh, it still fails with [2 s Could not find requested SDK org.freedesktop.Sdk//20.08beta (failure)](https://flathub.org/builds/#/builders/32/builds/23192)… :(

Does anyone know how to target flathub-beta instead of flathub for the SDK and Platform?

**Comment by linkmauve** [comment]
Thanks to everyone for the release of the freedesktop-sdk 20.08, this means poezio can finally enter Flathub, after waiting for close to two years!

However, despite [the build having succeeded](https://flathub.org/builds/#/builders/32/builds/26658), I still don’t see it at https://flathub.org/apps/search/poezio

Edit: never mind, [it’s there now](https://flathub.org/apps/details/io.poez.Poezio)!
